# Generated by Django 4.0.2 on 2022-04-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(default='', max_length=20)),
                ('owner_profession', models.CharField(default='', max_length=15)),
                ('plot_image', models.ImageField(default='', upload_to='static/')),
                ('selling_date', models.DateField(default='XXXX-XX-XX')),
                ('plot_desc', models.CharField(default='', max_length=150)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
