# Generated by Django 4.0.2 on 2022-04-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='district',
            field=models.CharField(default='', max_length=15),
        ),
    ]
