# Generated by Django 4.0.2 on 2022-04-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0003_plot_area_plot_latitude_plot_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plot_image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
