# Generated by Django 4.0.2 on 2022-04-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0004_alter_plot_plot_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='area',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_image',
            field=models.ImageField(default='', upload_to='static/'),
        ),
    ]
