# Generated by Django 4.0.2 on 2022-04-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0005_remove_plot_area_remove_plot_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
