# Generated by Django 4.0.2 on 2022-04-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0008_delete_address_alter_plot_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='plot_image',
        ),
    ]
