# Generated by Django 4.0.2 on 2022-05-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0009_remove_plot_plot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='contact',
            field=models.CharField(default='', max_length=11),
        ),
    ]
